#TODO use env variable
#TODO group id 98480539
#TODO admin id 1539221

gitlab:
  admin: 1539221
  personalAccessToken: ${GITLAB_PAT}
  url: "https://gitlab.com/"

spring:
  threads:
    virtual:
      enabled: true